### ISSUE TITLE
Autograder: [DESCRIBE BUG BEHAVIOR]

### ISSUE THREAD

**Issue by Dnam00** [comp426-2022-fall/a02#14]
#### Which autograder check is failing?
Run education/autograding@v1

#### What is happening?
It is saying that there is an unexpected token < in JSON at position 0. Maybe there is something else being sent to JSON that is not the correct text. 

#### Failed workflow run URL
https://github.com/comp426-2022-fall/a02-Dnam00/actions/runs/3268092974/jobs/5374098017

#### What should be happening?
JSON should be utilized correctly, as my local commands all work and utilize JSON correctly.

#### Screenshots of your local test(s)
<img width="678" alt="failed autograder test" src="https://user-images.githubusercontent.com/69867708/196273674-89a8b149-49e9-44b2-8d0e-b97cb1c171ad.png">

![Screenshot (18)](https://user-images.githubusercontent.com/69867708/196275161-926c0514-229c-47f9-980c-7024b9359a50.png)
![Screenshot (19)](https://user-images.githubusercontent.com/69867708/196275173-f12186ec-a701-48ba-8168-5a4d751b7069.png)
![Screenshot (20)](https://user-images.githubusercontent.com/69867708/196275189-1b5c2df8-9057-4f74-9562-acb97f0e4acf.png)

#### Why do you think the autograder is failing? 
I might have not downloaded JQ. I also am unable to perform npm unlink, but I can perform every other command. I also unexpectedly had to gitpull before pushing.

**Comment by jessikka12** [comment]
The autograder got removed during the merging process so we had to copy it over
