### ISSUE TITLE
Autograder: Module not found

### ISSUE THREAD

**Issue by annabellelj** [comp426-2022-fall/a02#16]
Which autograder check is failing?
All the ones besides the licenses are failing

What is happening?
It all says that Module not found, and it seems like there were two a02 files the test was trying to look through but there's only one when I checked on my end.

What should be happening?
Running the test

Screenshots of your local test(s)

<img width="1295" alt="Screenshot 2022-11-03 at 1 29 14 PM" src="https://user-images.githubusercontent.com/69731314/199804484-ebfb3e5a-6271-466e-aea7-6e5e3179c3e3.png">

Why do you think the autograder is failing? 
I think there's something wrong when I tried to add the file

**Comment by smelliskay** [comment]
Hi Annabelle.

I noticed that you have your file named "clis.js" rather than "cli.js". Try fixing that and if that doesn't correct anything then I'll look deeper into it.
