### ISSUE TITLE
I can't do git push, it worked a few days ago

### ISSUE THREAD

**Issue by Leo-TK1** [comp426-2022-fall/a02#18]
I can't do git push to push my work onto GH. It was working just fine a few days ago.

When I do 'git push' it asks for my username and password. Once I put that in, it still fails to recognize me. 

I tried adding a new SSH key but that still didn't fix the error.

**Comment by vennila-t** [comment]
Hey would you mind adding a screenshot of your error message as well? Easier to troubleshoot that way

**Comment by vennila-t** [comment]
Based on our interaction in OH, you have your GitHub origin set to HTTPS. You may need to update the origin for your repository to SSH if it is set to HTTPS. Do this to switch to SSH:

git remote -v
git remote set-url origin git@github.com:USERNAME/REPONAME.git
