### ISSUE TITLE
Clarification needed: [Setup - JQ Installation]

### ISSUE THREAD

**Issue by JadJ23** [comp426-2022-fall/a02#2]
#### URL of confusing thing

https://stedolan.github.io/jq/download/

#### What is confusing?

![image](https://user-images.githubusercontent.com/84463380/193637565-7ce66555-d579-4f83-910f-e7bf5890b51a.png)

trying to install JQ but getting message of not being able to locate the package

#### What did you read to try to understand better what is happening and solve the issue?

I read through the installation page and I googled the issue

**Comment by oizokun** [comment]
For anyone having this issue try running 
sudo apt-get update
then 
sudo apt-get install jq 
after
