### ISSUE TITLE
Runtime error: [require is not defined]

### ISSUE THREAD

**Issue by davissmith1** [comp426-2022-fall/a02#6]
#### What is happening?
I'm getting an error from when trying to require minimist and moment.
it said to use import instead that that also produces and error

#### What does the error say is happening?
that the 'require key word is not defined"
and its not a commonJS script

#### What do you think the error means?
Not really sure. im guessing it has something to do with the "type: modeule 

#### Command string
This file is being treated as an ES module because it has a '.js' file extension and '/Users/davissmith/Projects/Comp_426/a02-davissmith1/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Users/davissmith/Projects/Comp_426/a02-davissmith1/cli.js:3:18
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

#### Code snippet
const minimist = require('minimist')
const moment = require('moment')

**Comment by jdmar3** [comment]
See the 4 links under Modules here: https://github.com/comp426-2022-fall/schedule/blob/main/11-create-module.md#modules-nodejs-docs

Pay special attention to the last one if you want to use CommonJS `require`. You would have to add the following before your other dependencies:

```
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
```

But you can also just not use require and use ES method `import` instead:

```
import { minimist } from 'minimist';
import { moment } from 'moment';
```

**Comment by davissmith1** [comment]
Moment import is now working but I continue to get an error on the moment.tz.guess() call. 

const timezone = args.z || moment.tz.guess() ||  'America/New_York'
                                     ^

TypeError: Cannot read properties of undefined (reading 'guess')
    at file:///Users/davissmith/Projects/Comp_426/a02-davissmith1/cli.js:25:38
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)

not really sure whats wrong here
